// LCD used P/N: DE 133-RS-30/6,35/12° (3 VOLT)
// byte array[F E AN A G D B C dp]
// byte array[BP0 BP1 BP2 BP0 BP1 BP2 BP0 BP1 BP2]
#define BLANK 0b00000000
#define SEGA  0b00010000
#define SEGB  0b00000010
#define SEGC  0b00000001
#define SEGD  0b00000100
#define SEGE  0b01000000
#define SEGF  0b10000000
#define SEGG  0b00001000
#define SEGW  0b00100000 // Symbol "arrow down"

#define SPACE   (BLANK)
#define QUMARK  (SEGB|SEGF)
#define PERC    (SEGB|SEGE|SEGG)
#define APH     (SEGG)
#define OBRAC   (SEGA|SEGD|SEGE|SEGF)
#define CBRAC   (SEGA|SEGB|SEGC|SEGD)
#define MINUS   (SEGG)
#define DOT     (SEGP)
#define NUM0    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF)
#define NUM1    (SEGB|SEGC)
#define NUM2    (SEGA|SEGB|SEGD|SEGE|SEGG)
#define NUM3    (SEGA|SEGB|SEGC|SEGD|SEGG)
#define NUM4    (SEGB|SEGC|SEGF|SEGG)
#define NUM5    (SEGA|SEGC|SEGD|SEGF|SEGG)
#define NUM6    (SEGA|SEGC|SEGD|SEGE|SEGF|SEGG)
#define NUM7    (SEGA|SEGB|SEGC)
#define NUM8    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF|SEGG)
#define NUM9    (SEGA|SEGB|SEGC|SEGD|SEGF|SEGG)

#define LETA    (SEGA|SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETB    (SEGC|SEGD|SEGE|SEGF|SEGG)
#define LETC    (SEGA|SEGD|SEGE|SEGF)
#define LETD    (SEGB|SEGC|SEGD|SEGE|SEGG)
#define LETE    (SEGA|SEGD|SEGE|SEGF|SEGG)
#define LETF    (SEGA|SEGE|SEGF|SEGG)
#define LETG    (SEGA|SEGC|SEGD|SEGE|SEGF)
#define LETH    (SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETI    (SEGE|SEGF)
#define LETJ    (SEGB|SEGC|SEGD|SEGE)
#define LETK    (SEGA|SEGC|SEGE|SEGF|SEGG)
#define LETL    (SEGD|SEGE|SEGF)
#define LETM    (SEGA|SEGC|SEGE)
#define LETN    (SEGA|SEGB|SEGC|SEGE|SEGF)
#define LETO    (SEGA|SEGB|SEGC|SEGD|SEGE|SEGF)
#define LETP    (SEGA|SEGB|SEGE|SEGF|SEGG)
#define LETQ    (SEGA|SEGB|SEGC|SEGF|SEGG)
#define LETR    (SEGE|SEGG)
#define LETS    (SEGA|SEGC|SEGD|SEGF|SEGG)
#define LETT    (SEGD|SEGE|SEGF|SEGG)
#define LETU    (SEGB|SEGC|SEGD|SEGE|SEGF)
#define LETV    (SEGB|SEGC|SEGD|SEGF)
#define LETW    (SEGB|SEGD|SEGF)
#define LETX    (SEGB|SEGC|SEGE|SEGF|SEGG)
#define LETY    (SEGB|SEGC|SEGD|SEGF|SEGG)
#define LETZ    (SEGA|SEGB|SEGD|SEGG)
